Document: mono-llvm
Title: Debian mono-llvm Manual
Author: <insert document author here>
Abstract: This manual describes what mono-llvm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mono-llvm/mono-llvm.sgml.gz

Format: postscript
Files: /usr/share/doc/mono-llvm/mono-llvm.ps.gz

Format: text
Files: /usr/share/doc/mono-llvm/mono-llvm.text.gz

Format: HTML
Index: /usr/share/doc/mono-llvm/html/index.html
Files: /usr/share/doc/mono-llvm/html/*.html
